image: docker:latest

variables:
  REPOSITORY_URL: rezaakbar35/unit-test-development
  IMAGE_TAG: latest

services:
- docker:dind

before_script:
  - docker login --username=$DH_USERNAME --password=$DH_PASSWORD

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building image..."
    - docker build 
      -t to-do:latest 
      --build-arg PORT=$PORT 
      --no-cache .
    - echo "Tagging image..."
    - docker tag to-do:latest $REPOSITORY_URL:latest
    - echo "Pushing image..."
    - docker push $REPOSITORY_URL:latest
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker stop to-do || true && docker rm to-do || true
    - docker container run -dt -p $PORT:$PORT --name to-do $REPOSITORY_URL:latest
    - docker image prune -f
  only:
    - master